language: scala

jdk:
 - oraclejdk7
 - oraclejdk8

sudo: false

scala:
  - 2.11.6
  - 2.10.5
  - 2.9.3

matrix:
  exclude:
    - scala: "2.9.3" # Scala 2.9.x does not support java8
      jdk: oraclejdk8
